function getGreenTextHtml(text: string) : string {
    return `<span style=\'color: green;\'>${text}</span>`;
}

function getRedTextHtml(text: string) : string {
    return `<span style=\'color: red;\'>${text}</span>`;
}

function gainOrLose(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0 ) {
            return 'Gain';
        }
        else {
            return 'Lose';
        }
    }

    return amount;
}

function coloredNumber(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0 ) {
            return getGreenTextHtml(amount);
        }
        else {
            return getRedTextHtml(amount);
        }
    }

    return amount;
}

function coloredNumberSigned(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0 ) {
            return `+${getGreenTextHtml(amount)}`;
        }
        else {
            return `-${getRedTextHtml(amount)}`;
        }
    }

    return amount;
}

function numberSigned(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0 ) {
            return `+${amount}`;
        }
        else {
            return `-${amount}`;
        }
    }

    return amount;
}

function coloredPercentage(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0) {
            return displayPercentage(`${getGreenTextHtml(amount)}`);
        }
        else {
            return displayPercentage(`${getRedTextHtml(amount)}`);
        }
    }

    return amount;
}

function coloredPercentageSigned(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0) {
            return displayPercentage(`+${getGreenTextHtml(amount)}`);
        }
        else {
            return displayPercentage(`-${getRedTextHtml(amount)}`);
        }
    }

    return amount;
}

function displayPercentageSigned(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 0) {
            return displayPercentage(`+${amount}`);
        }
        else {
            return displayPercentage(`-${amount}`);
        }
    }

    return amount;
}

function displayPercentage(text: string) : string {
    return `${text}%`;
}

function numberToPercentage(amount: string) : number {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
       return amountNumber / 100;
    }

    return 0;
}

function pluralOrSingle(amount: string, single: string, pluralOrSingle: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
        if(amountNumber > 1 ) {
            return pluralOrSingle;
        }
        else {
            return single;
        }
    }

    return amount;
}

function textInQuotes(text: string) : string {
    return `"${text}"`;
}

function numberFromPercetage(amount: string) : string {
    var amountNumber = Number(amount);
    if(!Number.isNaN(amountNumber)) {
       return (amountNumber * 100).toString();
    }

    return amount;
}

function ifElseThen(input: boolean, met: string, unmet: string) : string {
    return input ? met : unmet;
}

function toNumber(amount: string) : number {
    var amountNumber = Number(amount);
    if(Number.isNaN(amountNumber)) {
        return 0;
    }

    return amountNumber;
}

const msgKey = new Map<string, Function>([
    ["MsgUnprocessed", (msg: string) => msg],
    ["MsgYes", (icon: string) => `${icon} Yes`],
    ["MsgNo", (icon: string) => `${icon} No`],
    ["MsgAddCardinal", () => "Gain a cardinal"],
    ["MsgHeirDies", () => "Heir dies"],
    ["MsgRulerDies", () => "Ruler dies"],
    ["MsgLoseCardinal", () => "Lose a cardinal"],
    ["MsgLeaveHRE", () => "Remove all provinces from the Holy Roman Empire, unless an elector or the Emperor"],
    ["MsgIsJanissaryMod", () => "(This is a Janissary modifier.)"],
    ["MsgGainADM", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} administrative power`],
    ["MsgGainAT", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} army tradition`],
    ["MsgGainAuth", (amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} authority`],
    ["MsgDrillGainMod", (amount: string) => coloredNumber(amount) + " Army drill gain modifier"],
    ["MsgGainBT", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} base tax`],
    ["MsgGainBP", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} base production`],
    ["MsgGainBM", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} base manpower`],
    ["MsgGainDIP", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} diplomatic power`],
    ["MsgGainDoom", (amount: string) => `${gainOrLose(amount)} ${amount} doom`],
    ["MsgHeirGainClaim", (amount: string) => `Heir ${gainOrLose(amount)} ${coloredNumber(amount)} claim strength`],
    ["MsgGainDevotion", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} devotion`],
    ["MsgGainHordeUnity", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} horde unity`],
    ["MsgGainImperialAuthority", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} imperial authority`],
    ["MsgGainKarma", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} karma`],
    ["MsgGainLegitimacy", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} legitimacy`],
    ["MsgGainMIL", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} military power`],
    ["MsgGainNavyTradition", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} navy tradition`],
    ["MsgGainPapalInfluence", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} papal influence`],
    ["MsgGainPrestige", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} prestige`],
    ["MsgGainRepTrad", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} republican tradition`],
    ["MsgGainStability", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} stability`],
    ["MsgGainWarExhaustion", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} war exhaustion`],
    ["MsgGainYearlyManpower", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} ${pluralOrSingle(amount, "year's", "years'")} worth of manpower`],
    ["MsgGainADMSkill", (icon: string, amount: string) => `Ruler ${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} administrative skill`],
    ["MsgGainDIPSkill", (icon: string, amount: string) => `Ruler ${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} diplomatic skill`],
    ["MsgGainMILSkill", (icon: string, amount: string) => `Ruler ${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} military skill`],
    ["MsgGainSiegeProgress", (amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} siege progress`],
    ["MsgGainPatAuth", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredPercentage(numberFromPercetage(amount))} Patriarch authority`],


    // instead use add_piety
    // ["MsgGainMysticism", (icon: string, amount: string) => `Gain ${icon} '''${reducedNum(plainNum, -amount)}''' Mysticism`],
    // ["MsgGainLegalism", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${reducedNum(plainNum, amount)} ${ifElseThen( amount < 0, "Mysticism", "Legalism")}`],


    // instead use change_statists_vs_orangists
    // ["MsgStrengthenStatists", (icon: string, amount: string) => `Strengthen ${icon} Statists by '''${reducedNum(plainPc, -amount)}'''`],
    // ["MsgStrengthenOrangists", (icon: string, amount: string) => `Strengthen ${icon} Orangists by '''${coloredNumber(amount)}'''`],


    ["MsgGainInflation", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${displayPercentage(amount)} inflation`],
    ["MsgGainLocalAutonomy", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${displayPercentage(amount)} local autonomy`],
    ["MsgReformDesire", (icon: string, amount: string) => `{{icon|catholic}} Catholicism has at least ${icon} ${displayPercentage(numberFromPercetage(amount))} reform desire`],
    ["MsgGainReformDesire", (icon: string, amount: string) => `{{icon|catholic}} Catholicism ${gainOrLose(amount)} ${icon} ${displayPercentage(numberFromPercetage(amount))} reform desire`],
    ["MsgGainMercantilism", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredPercentage(amount)} mercantilism`],
    ["MsgGainMP", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} manpower`],
    ["MsgGainMPFrac", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} manpower equal to ${coloredPercentage(numberFromPercetage(amount))} of maximum`],
    ["MsgSeparatism", (icon: string, amount: string) => `Has at least ${icon} ${amount} ${pluralOrSingle(amount, "year", "years")} of separatism`],
    ["MsgCountryMod", () => "country modifier"],
    ["MsgProvMod", () => "province modifier"],
    ["MsgPermanentProvMod", () => "permanent province modifier"],
    ["MsgRulerMod", () => "ruler modifier"],
    ["MsgTradeMod", () => "trade modifier"],
    ["MsgAddMod", (modid: string, name: string, days: string) => `Gain modifier ${textInQuotes(name)} <!-- ${modid} --> for ${days} days`],
    ["MsgGainMod", (modid: string, type: string, name: string) => `Gain ${type} ${textInQuotes(name)}, <!-- ${modid} --> giving the following effects:`],
    ["MsgGainModDur", (modid: string, type: string, name: string, days: string) => `Gain ${type} ${textInQuotes(name)} <!-- ${modid} --> for ${Number(days) < 0 ? (type === "ruler" ? "the duration of the current ruler's reign" : "the rest of the game") : `${days} ${pluralOrSingle(days, "day", "days")}`} , giving the following effects:`],
    ["MsgGainModPow", (modid: string, type: string, name: string, pow: string) => `Gain ${type} ${textInQuotes(name)} <!-- ${modid} --> (${coloredNumberSigned(pow)} Power)`],
    ["MsgGainModPowDur", (modid: string, type: string, name: string, pow: string, days: string) => `Gain ${type} ${textInQuotes(name)} <!-- ${modid} --> (${coloredNumberSigned(pow)} Power) for ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgActorGainsMod", (modid: string, who: string, type: string, name: string) => `${who} gains ${type} ${textInQuotes(name)} <!-- ${modid} --> giving the following effects:`],
    ["MsgActorGainsModDur", (modid: string, who: string, type: string, name: string, days: string) => `${who} gains ${type} ${textInQuotes(name)} <!-- ${modid} --> for ${days} ${pluralOrSingle(days, "day", "days")} , giving the following effects:`],
    ["MsgActorGainsModPow", (modid: string, who: string, type: string, name: string, pow: string) => `${who} gains ${type} ${textInQuotes(name)} <!-- ${modid} --> (${coloredNumberSigned(pow)} Power)`],
    ["MsgActorGainsModPowDur", (modid: string, who: string, type: string, name: string, pow: string, days: string) => `${who} gains ${type} ${textInQuotes(name)} <!-- ${modid} --> (${coloredNumberSigned(pow)} Power) for ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgHasModifier", (modid: string, kind: string, name: string) => `Has ${kind} ${textInQuotes(name)} <!-- ${modid} -->`],
    ["MsgRemoveModifier", (modid: string, kind: string, name: string) => `Remove ${kind} ''"${name}"'' <!-- ${modid} -->`],
    ["MsgAllOf", () => "All of:"],
    ["MsgFROM", () => "FROM:"],
    ["MsgROOT", () => "ROOT"],
    ["MsgROOTCountry", () => "Our country"],
    ["MsgROOTCountryAsOther", () => "same as our country"],
    ["MsgROOTProvince", () => "The currently considered province"],
    ["MsgROOTProvinceOwner", () => "the owner of the currently considered province"],
    ["MsgROOTProvinceAsOther", () => "same as the currently considered province"],
    ["MsgROOTTradeNode", () => "The currently considered trade node"],
    ["MsgROOTGeographic", () => "The currently considered location"],
    ["MsgPREV", () => "PREV"],
    ["MsgPREVCountry", () => "Previously mentioned country"],
    ["MsgPREVCountryAsOther", () => "same as the previously mentioned country"],
    ["MsgPREVProvince", () => "The previously mentioned province"],
    ["MsgPREVProvinceOwner", () => "the owner of the previously mentioned province"],
    ["MsgPREVProvinceAsOther", () => "same as the previously mentioned province"],
    ["MsgPREVTradeNode", () => "The previously mentioned trade node"],
    ["MsgPREVGeographic", () => "The previously mentioned location"],
    ["MsgTHISCountry", () => "this country"],
    ["MsgTHISCountryAsOther", () => "same as this country"],
    ["MsgTHISProvince", () => "this province"],
    ["MsgTHISProvinceOwner", () => "the owner of this province"],
    ["MsgTHISProvinceAsOther", () => "same as this province"],
    ["MsgTHISTradeNode", () => "This trade node"],
    ["MsgTHISGeographic", () => "This location"],
    ["MsgEmperor", () => "The Holy Roman Emperor"],
    ["MsgOriginalDynasty", () => "the country's original dynasty"],
    ["MsgHistoricDynasty", () => "one of the country's historical dynasties"],
    ["MsgNoneOf", () => "None of:"],
    ["MsgAllCoreProvince", () => "All core provinces:"],
    ["MsgAllProvince", () => "All provinces:"],
    ["MsgAllSubjectCountries", () => "All subject countries:"],
    ["MsgArea", () => "Area containing this province:"],
    ["MsgAtLeastOneOf", () => "At least one of:"],
    ["MsgAnyActiveTradeNode", () => "Any trade node with a merchant present:"],
    ["MsgAnyAlly", () => "Any ally:"],
    ["MsgAnyCoreCountry", () => "Any country with a core on this province:"],
    ["MsgAnyCoreProvince", () => "Any core province:"],
    ["MsgAnyCountry", () => "Any country in the world:"],
    ["MsgAnyEmptyNeighborProvince", () => "Any neighbouring uncolonized province:"],
    ["MsgAnyEnemyCountry", () => "Any enemy country:"],
    ["MsgAnyHereticProvince", () => "Any province with heretic religion:"],
    ["MsgAnyKnownCountry", () => "Any known country:"],
    ["MsgAnyNeighborCountry", () => "Any neighbouring country:"],
    ["MsgAnyNeighborProvince", () => "Any neighbouring province:"],
    ["MsgAnyOwnedProvince", () => "Any owned province:"],
    ["MsgAnyPrivateeringCountry", () => "Any country privateering in this node:"],
    ["MsgAnyProvince", () => "Any province:"],
    ["MsgAnyRival", () => "Any rival:"],
    ["MsgAnySubject", () => "Any subject:"],
    ["MsgAnyTradeNode", () => "Any trade node:"],
    ["MsgCapital", () => "Capital"],
    ["MsgController", () => "Province controller"],
    ["MsgElse", () => "Else:"],
    ["MsgAllCountries", () => "All countries in the world:"],
    ["MsgAllNeighborCountries", () => "All neighbouring countries:"],
    ["MsgEveryActiveTradeNode", () => "Every trade node with a merchant present:"],
    ["MsgEveryAlly", () => "Every ally:"],
    ["MsgEveryCountry", () => "Every country in the world:"],
    ["MsgEveryCoreCountry", () => "Every country with a core:"],
    ["MsgEveryCoreProvince", () => "Every core province:"],
    ["MsgEveryEnemyCountry", () => "Every enemy country:"],
    ["MsgEveryHereticProvince", () => "Every province with heretic religion:"],
    ["MsgEveryKnownCountry", () => "Every known country:"],
    ["MsgEveryNeighborCountry", () => "Every neighbouring country:"],
    ["MsgEveryNeighborProvince", () => "Every neighbouring province:"],
    ["MsgEveryOwnedProvince", () => "Every owned province:"],
    ["MsgEveryProvince", () => "Every province in the world:"],
    ["MsgEveryRival", () => "Every rival:"],
    ["MsgEverySubject", () => "Every subject country:"],
    ["MsgHiddenEffect", () => "Hidden effect:"],
    ["MsgIf", () => "If:"],
    ["MsgLimit", () => "Limited to:"],
    ["MsgMostProvinceTradePower", () => "The country with the most provincial trade power:"],
    ["MsgOverlord", () => "Overlord:"],
    ["MsgOwner", () => "Province owner:"],
    ["MsgRandomActiveTradeNode", () => "One random trade node with a merchant present:"],
    ["MsgRandomAlly", () => "One random ally:"],
    ["MsgRandomCoreCountry", () => "One random country with a core:"],
    ["MsgRandomCoreProvince", () => "One random core province:"],
    ["MsgRandomCountry", () => "One random country:"],
    ["MsgRandomElector", () => "One random elector:"],
    ["MsgRandomEmptyNeighborProvince", () => "One random neighbouring uncolonized province:"],
    ["MsgRandomHereticProvince", () => "One random province with heretic religion:"],
    ["MsgRandomKnownCountry", () => "One random known country:"],
    ["MsgRandomList", () => "One of the following at random:"],
    ["MsgRandomNeighborCountry", () => "One random neighbouring country:"],
    ["MsgRandomNeighborProvince", () => "One random neighbouring province:"],
    ["MsgRandomOwnedProvince", () => "One random owned province:"],
    ["MsgRandomPrivateeringCountry", () => "One random country privateering in this node:"],
    ["MsgRandomProvince", () => "One random province:"],
    ["MsgRandomRival", () => "One random rival:"],
    ["MsgRandomSubjectCountry", () => "One random subject country:"],
    ["MsgRandomTradeNode", () => "One random trade node:"],
    ["MsgStrongestTradePower", () => "The country with the most trade power:"],
    ["MsgWhile", () => "While:"],
    ["MsgRandomChance", (chance: string) => `${numberToPercentage(chance)} chance of:`],
    ["MsgRandom", () => "One of the following at random:"],
    ["MsgChangeGovernment", (what: string) => `Change government to ${what}`],
    ["MsgContinentIs", (what: string) => `Continent is ${what}`],
    ["MsgContinentIsAs", (what: string) => `Continent is the same as ${what}`],
    ["MsgCultureIs", (what: string) => `Culture is ${what}`],
    ["MsgCultureIsAs", (who: string) => `Culture is the same as ${who}`],
    ["MsgCultureIsGroup", (what: string) => `Culture is in ${what} group`],
    ["MsgCultureGroupAs", (what: string) => `Culture is in the same group as ${what}`],
    ["MsgRulerIsDynasty", (what: string) => `Ruler is of ${what} dynasty`],
    ["MsgRulerIsSameDynasty", (who: string) => `Ruler is of the same dynasty as ${who}`],
    ["MsgHeirNationality", (what: string) => `Heir's culture is ${what}`],
    ["MsgHeirNationalityAs", (who: string) => `Heir's culture is the same as ${who}`],
    ["MsgHeirReligion", (icon: string, what: string) => `Heir's religion is ${icon} ${what}`],
    ["MsgHeirReligionAs", (who: string) => `Heir's religion is the same as ${who}`],
    ["MsgSetHeirReligion", (icon: string, what: string) => `Heir's religion becomes ${icon} ${what}`],
    ["MsgSetHeirReligionAs", (who: string) => `Heir's religion becomes that of ${who}`],
    ["MsgDisasterEnds", (what: string) => `Disaster ${textInQuotes(what)} ends`],
    ["MsgGovernmentIs", (what: string) => `Government is ${what}`],
    ["MsgGovernmentIsIcon", (icon: string, what: string) => `Government is ${icon} ${what}`],
    ["MsgHasAdvisor", (whom: string) => `Has advisor ${whom}`],
    ["MsgHasAdvisorType", (icon: string, what: string) => `Has ${icon} ${what} advisor`],
    ["MsgHasTerrain", (what: string) => `Has ${what} terrain`],
    ["MsgCavalrySpawnsCountry", (whom: string) => `A cavalry regiment loyal to ${whom} spawns`],
    ["MsgCavalrySpawnsProvince", (where: string) => `A cavalry regiment spawns in ${where}`],
    ["MsgInfantrySpawnsCountry", (whom: string) => `An infantry regiment loyal to ${whom} spawns`],
    ["MsgInfantrySpawnsProvince", (where: string) => `An infantry regiment spawns in ${where}`],
    ["MsgAdvisorDies", (who: string) => `Advisor ${who} dies`],
    ["MsgPrimaryCultureIs", (what: string) => `Primary culture is ${what}`],
    ["MsgPrimaryCultureIsAs", (what: string) => `Primary culture is the same as ${what}`],
    ["MsgRegionIs", (what: string) => `Province is in ${what} region`],
    ["MsgLoseAdvisor", (who: string) => `Advisor ${who} leaves the country's court`],
    ["MsgRemoveFromEstate", (icon: string, whom: string) => `Remove province from the ${icon} ${whom} estate`],
    ["MsgDisasterOngoing", (what: string) => `The ${textInQuotes(what)} disaster is ongoing`],
    ["MsgProvinceIs", (what: string) => `Province is ${what}`],
    ["MsgOwns", (what: string) => `Owns province ${what}`],
    ["MsgOwnsCore", (what: string) => `Owns core province ${what}`],
    ["MsgControls", (what: string) => `Controls province ${what}`],
    ["MsgAdvisorExists", (advisorID: string) => `Advisor with ID ${advisorID} exists`],
    ["MsgAdvisorIsEmployed", (advisorID: string) => `Advisor with ID ${advisorID} is employed`],
    ["MsgClearFlag", (flagType: string, name: string) => `Clear ${flagType} flag <tt>${name}</tt>`],
    ["MsgHasFlag", (flagType: string, name: string) => `${flagType} flag <tt>${name}</tt> is set`],
    ["MsgSetFlag", (flagType: string, name: string) => `Set ${flagType} flag <tt>${name}</tt>`],
    ["MsgHadFlag", (category: string, name: string, days: string) => `Has had ${category} flag ${name} for ${days} days`],
    ["MsgCountryFlag", () => "country"],
    ["MsgProvinceFlag", () => "province"],
    ["MsgRulerFlag", () => "ruler"],
    ["MsgGlobalFlag", () => "global"],
    ["MsgHadCountryFlag", (name: string, days: string) => `Has had country flag <tt>${name}</tt> for at least ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgHadProvinceFlag", (name: string, days: string) => `Has had province flag <tt>${name}</tt> for at least ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgHadRulerFlag", (name: string, days: string) => `Has had ruler flag <tt>${name}</tt> for at least ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgHadGlobalFlag", (name: string, days: string) => `Global flag <tt>${name}</tt> has been set for at least ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgColonySettlers", (amount: string) => `Colony has at least ${amount} ${pluralOrSingle(amount, "settler", "settlers")}`],
    ["MsgWasAtWar", (amount: string) => `Was at war within the last ${amount} ${pluralOrSingle(amount, "month", "months")}`],
    ["MsgHeirAge", (amount: string) => `Heir is at least ${amount} ${pluralOrSingle(amount, "year", "years")} old`],
    ["MsgYearIs", (amount: string) => `Year is ${amount} or later`],
    ["MsgNumLoans", (amount: string) => `Has at least ${amount} ${pluralOrSingle(amount, "loan", "loans")}`],
    ["MsgNumMercs", (amount: string) => `Has at least ${amount} mercenary ${pluralOrSingle(amount, "regiment", "regiments")}`],
    ["MsgNumMissionaries", (icon: string, amount: string) => `Has at least ${icon} ${amount} ${pluralOrSingle(amount, "missionary", "missionaries")}`],
    ["MsgNumPorts", (amount: string) => `Has at least ${amount} ${pluralOrSingle(amount, "port", "ports")}`],
    ["MsgNumRebelArmies", (amount: string) => `At least ${amount} rebel ${pluralOrSingle(amount, "army is", "armies are")} present in the country`],
    ["MsgNumEmbargoes", (amount: string) => `Is embargoing at least ${amount} other ${pluralOrSingle(amount, "country", "countries")}`],
    ["MsgUnitsInProvince", (amount: string) => `Province contains at least ${amount} ${pluralOrSingle(amount, "regiment", "regiments")}`],
    ["MsgNumCities", (amount: string) => `Owns at least ${amount} non-colony ${pluralOrSingle(amount, "province", "provinces")}`],
    ["MsgNumCitiesThan", (whom: string) => `Owns at least as many cities as ${whom}`],
    ["MsgToleranceToThis", (amount: string) => `Tolerance to this religion is at least ${coloredNumber(amount)}`],
    ["MsgRulerADM", (icon: string, amount: string) => `Ruler's ${icon} administrative skill is at least ${amount}`],
    ["MsgADMTech", (icon: string, amount: string) => `Administrative technology is at least ${icon} ${amount}`],
    ["MsgArmyTradition", (icon: string, amount: string) => `Army tradition is at least ${icon} ${amount}`],
    ["MsgArmyTraditionFromBattles", (icon: string, amount: string) => `${icon} ${coloredNumber(amount)} Army tradition from battles`],
    ["MsgYearlyArmyTradition", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Yearly army tradition`],
    ["MsgBaseManpower", (icon: string, amount: string) => `${icon} Base manpower is at least ${amount}`],
    ["MsgBaseProduction", (icon: string, amount: string) => `${icon} Base production is at least ${amount}`],
    ["MsgBaseTax", (icon: string, amount: string) => `${icon} Base tax is at least ${amount}`],
    ["MsgCreateAdmiral", (icon: string, amount: string) => `Gain ${icon} admiral with ${amount} navy tradition`],
    ["MsgCreateConquistador", (icon: string, amount: string) => `Gain ${icon} conquistador with ${amount} navy tradition`],
    ["MsgCreateExplorer", (icon: string, amount: string) => `Gain ${icon} explorer with ${amount} navy tradition`],
    ["MsgCreateGeneral", (icon: string, amount: string) => `Gain ${icon} general with ${amount} army tradition`],
    ["MsgDevelopment", (icon: string, development: string) => `${icon} Development is at least ${development}`],
    ["MsgRulerDIP", (icon: string, amount: string) => `Ruler's ${icon} diplomatic skill is at least ${amount}`],
    ["MsgDIPTech", (icon: string, amount: string) => `${icon} Diplomatic technology is at least ${amount}`],
    ["MsgHordeUnity", (icon: string, amount: string) => `${icon} Horde unity is at least ${amount}`],
    ["MsgYearlyHordeUnity", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Yearly horde unity`],
    ["MsgKarma", (icon: string, amount: string) => `${icon} Karma is at least ${coloredPercentage(amount)}`],
    ["MsgLegitimacy", (icon: string, amount: string) => `${icon} Legitimacy is at least ${amount}`],
    ["MsgYearlyLegitimacy", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Yearly legitimacy`],
    ["MsgRulerMIL", (icon: string, amount: string) => `Ruler's ${icon} military skill is at least ${amount}`],
    ["MsgMILTech", (icon: string, amount: string) => `${icon} Military technology is at least ${amount}`],
    ["MsgNumAllies", (icon: string, amount: string) => `Has at least ${icon} ${amount} ${pluralOrSingle(amount, "ally", "allies")}`],
    ["MsgNumCardinals", (icon: string, amount: string) => `Has at least ${icon} ${amount} ${pluralOrSingle(amount, "cardinal", "cardinals")}`],
    ["MsgNumColonists", (icon: string, amount: string) => `Has at least ${icon} ${amount} ${pluralOrSingle(amount, "colonist", "colonists")}`],
    ["MsgNumHeavyShips", (icon: string, amount: string) => `Has at least ${icon} ${amount} heavy ${pluralOrSingle(amount, "ship", "ships")}`],
    ["MsgNumLightShips", (icon: string, amount: string) => `Has at least ${icon} ${amount} light ${pluralOrSingle(amount, "ship", "ships")}`],
    ["MsgNumMerchants", (icon: string, amount: string) => `Has at least ${icon} ${amount} ${pluralOrSingle(amount, "merchant", "merchants")}`],
    ["MsgStability", (icon: string, amount: string) => `${icon} Stability is at least ${coloredNumberSigned(amount)}`],
    ["MsgTotalDevelopment", (icon: string, amount: string) => `Country's total ${icon} development is at least ${amount}`],
    ["MsgTotalCardinals", (icon: string, amount: string) => `At least ${icon} ${amount} ${pluralOrSingle(amount, "cardinal", "cardinals")} exist in the world`],
    ["MsgUnrest", (icon: string, amount: string) => `Unrest is at least ${icon} ${amount}`],
    ["MsgMonthlyIncome", (icon: string, amount: string) => `${icon} Monthly income is at least ${coloredNumber(amount)} ducats`],
    ["MsgWarExhaustion", (icon: string, amount: string) => `${icon} War exhaustion is at least ${amount}`],
    ["MsgMonthlyWarExhaustion", (icon: string, amount: string) => `${icon} ${amount} Monthly war exhaustion`],
    ["MsgWarScore", (icon: string, amount: string) => `War score is at least ${icon} ${coloredPercentage(amount)}`],
    ["MsgRepTrad", (icon: string, amount: string) => `${icon} Republican tradition is at least ${amount}`],
    ["MsgYearlyRepTrad", (icon: string, amount: string) => `${icon} ${coloredNumber(amount)} Yearly republican tradition`],
    ["MsgInflation", (icon: string, amount: string) => `${icon} Inflation is at least ${displayPercentage(amount)}`],
    ["MsgLocalAutonomy", (icon: string, amount: string) => `${icon} Local autonomy is at least ${displayPercentage(amount)}`],
    ["MsgManpower", (icon: string, amount: string) => `Has at least ${icon} ${toNumber(amount) * 1000} manpower`],
    ["MsgManpowerPercentage", (icon: string, amount: string) => `${icon} Manpower reserves are at least ${numberToPercentage(amount)} of maximum`],
    ["MsgMercantilism", (icon: string, amount: string) => `${icon} Mercantilism is at least ${amount}`],
    ["MsgChangeGoods", (icon: string, what: string) => `Change province's goods produced to ${icon} ${what}`],
    ["MsgCreateAdvisor", (icon: string, what: string) => `Gain ${icon} ${what} advisor`],
    ["MsgHasIdeaGroup", (icon: string, what: string) => `Has activated ${icon} ${what}`],
    ["MsgProducesGoods", (icon: string, what: string) => `Produces ${icon} ${what}`],
    ["MsgProducesSameGoods", (where: string) => `Produces the same goods as ${where}`],
    ["MsgEstateExists", (icon: string, what: string) => `${icon} ${what} estate exists`],
    ["MsgHasEstate", (icon: string, what: string) => `Has estate ${icon} ${what}`],
    ["MsgAssignToEstate", (icon: string, what: string) => `Assign province to the ${icon} ${what} estate`],
    ["MsgRulerIsGeneral", (icon: string) => `Ruler is a ${icon} general`],
    ["MsgAlliedWith", (whom: string) => `Is allied to ${whom}`],
    ["MsgCedeProvinceTo", (whom: string) => `Cede province to ${whom}`],
    ["MsgControlledBy", (whom: string) => `Province is controlled by ${whom}`],
    ["MsgDefensiveWarAgainst", (whom: string) => `Is defending in a war against ${whom}`],
    ["MsgDiscoverCountry", (whom: string) => `Discover ${whom}`],
    ["MsgDiscoverProvince", (what: string) => `Discover ${what}`],
    ["MsgGainClaim", (who: string) => `${who} gains a claim on this province`],
    ["MsgGainPermanentClaimCountry", (who: string) => `${who} gains a permanent claim on this province`],
    ["MsgGainPermanentClaimProvince", (where: string) => `Gain a permanent claim on ${where}`],
    ["MsgHasDiscovered", (whomOrWhere: string) => `Has discovered ${whomOrWhere}`],
    ["MsgDiscoveredBy", (whom: string) => `Has been discovered by ${whom}`],
    ["MsgInherit", (whom: string) => `Inherit ${whom}`],
    ["MsgNeighbors", (whom: string) => `Has a border with ${whom}`],
    ["MsgIsRival", (whom: string) => `${whom} is a rival`],
    ["MsgIsSubjectOf", (whom: string) => `Is a subject of ${whom}`],
    ["MsgLoseCoreCountry", (who: string) => `${who} loses their core on this province`],
    ["MsgLoseCoreProvince", (where: string) => `Lose core on ${where}`],
    ["MsgRoyalMarriageWith", (whom: string) => `Has a royal marriage with ${whom}`],
    ["MsgOffensiveWarAgainst", (whom: string) => `Is attacking in a war against ${whom}`],
    ["MsgOwnedBy", (whom: string) => `Province is owned by ${whom}`],
    ["MsgReleaseVassal", (whom: string) => `Release ${whom} as a vassal`],
    ["MsgUnderSiegeBy", (whom: string) => `Province is under siege by ${whom}`],
    ["MsgSupportIndependenceOf", (whom: string) => `Support the independence of ${whom}`],
    ["MsgCountryIs", (who: string) => `Is ${who}`],
    ["MsgTruceWith", (whom: string) =>  `Has a truce with ${whom}`],
    ["MsgAtWarWith", (whom: string) => `Is at war with ${whom}`],
    ["MsgMakeWhitePeace", (whom: string) => `Make a white peace with ${whom}`],
    ["MsgCountryExists", (who: string) => `${who} exists`],
    ["MsgExists", (yn: boolean) => `${ifElseThen(yn, "Exists", "Does ''not'' exist")}`],
    ["MsgSameReligion", (whom: string) => `Religion is same as ${whom}`],
    ["MsgReligion", (icon: string, what: string) => `Religion is ${icon} ${what}`],
    ["MsgSameReligionGroup", (whom: string) => `Religion group is same as ${whom}`],
    ["MsgReligionGroup", (what: string) => `Religion is in ${what} group`],
    ["MsgChangeSameReligion", (whom: string) => `Change religion to that of ${whom}`],
    ["MsgChangeReligion", (icon: string, what: string) => `Change religion to ${icon} ${what}`],
    ["MsgIsCoreOf", (whom: string) => `Is a core of ${whom}`],
    ["MsgHasCoreOn", (what: string) => `Has a core on ${what}`],
    ["MsgHasClaim", (who: string) => `${who} has a claim on this province`],
    ["MsgHasClaimOn", (what: string) => `Has a claim on ${what}`],
    ["MsgIsAIControlled", (yn: boolean) => `Is ${ifElseThen(yn, "AI", "player")}-controlled`],
    ["MsgHasCardinal", (yn: boolean) => `${ifElseThen(yn, "Has", "Does ''not'' have")} a cardinal`],
    ["MsgHasHeir", (yn: boolean) => `${ifElseThen(yn, "Has", "Does ''not'' have")} an heir`],
    ["MsgHasOwnerCulture", (yn: boolean) => `Has ${ifElseThen(yn, "the same culture as", "a different culture from")} its owner`],
    ["MsgHasOwnerReligion", (yn: boolean) => `Has ${ifElseThen(yn, "the same religion as", "a different religion from")} its owner`],
    ["MsgHasPort", (yn: boolean) => `${ifElseThen(yn, "Has", "Does ''not'' have")} a port`],
    ["MsgHasSeatInParliament", (yn: boolean) => `${ifElseThen(yn, "Has", "Does ''not'' have")} a seat in Parliament`],
    ["MsgIsInRegency", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} in a regency`],
    ["MsgUnderSiege", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} under siege`],
    ["MsgAtWar", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} at war`],
    ["MsgIsCapital", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} the country's capital`],
    ["MsgIsCity", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} a city`],
    ["MsgIsColony", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} a colony`],
    ["MsgIsEmperor", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} the Holy Roman Emperor`],
    ["MsgIsFemale", (yn: boolean) => `Ruler is ${ifElseThen(yn, "female", "male")}`],
    ["MsgIsLesserInUnion", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} a lesser partner in a personal union`],
    ["MsgIsLooted", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} looted`],
    ["MsgIsOverseas", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} overseas`],
    ["MsgIsPartOfHRE", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} part of the Holy Roman Empire`],
    ["MsgIsCenterOfReformation", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} a Center of Reformation`],
    ["MsgIsSubject", (yn: boolean) => `Is${ifElseThen(yn, "", " ''not''")} a subject nation`],
    ["MsgPapacyIsActive", (yn: boolean) => `Papal interaction is${ifElseThen(yn, "", " ''not''")} active`],
    ["MsgHasBeenPlayer", (yn: boolean) => `Has${ifElseThen(yn, "", " ''never''")} been player-controlled`],
    ["MsgIsStatistsInPower", (yn: boolean) => `The {{icon|republic}} Statists are${ifElseThen(yn, "", " ''not''")} in power`],
    ["MsgIsOrangistsInPower", (yn: boolean) => `The {{icon|monarchy}} Orangists are${ifElseThen(yn, "", " ''not''")} in power`],
    ["MsgGainCB", (cbtype: string, whom: string) => `Gain ${cbtype} casus belli against ${whom}`],
    ["MsgGainCBDuration", (cbtype: string, whom: string, months: string) => `Gain ${cbtype} casus belli against ${whom} for ${months} months`],
    ["MsgReverseGainCB", (cbtype: string, who: string) => `${who} gains ${cbtype} casus belli against this country`],
    ["MsgReverseGainCBDuration", (cbtype: string, who: string, months: string) => `${who} gains ${cbtype} casus belli against this country for ${months} months`],
    ["MsgFactionGainInfluence", (icon: string, whom: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} influence for the ${whom} faction`],
    ["MsgFactionInPower", (icon: string, whom: string) => `${icon} ${whom} faction is in power`],
    ["MsgHasFactions", (yn: boolean) => `${ifElseThen(yn, "Has", "Does ''not'' have")} factions`],
    ["MsgHasBuilding", (icon: string, what: string) => `Has ${icon} ${what} building`],
    ["MsgIndefinitely", () => "indefinitely"],
    ["MsgForDays", (days: string) => `for ${days} days`],
    ["MsgEstateLoyalty", (icon: string, who: string, amount: string) => `${icon} ${who} has at least ${amount} loyalty`],
    ["MsgEstateInfluence", (icon: string, who: string, amount: string) => `${icon} ${who} has at least ${amount} influence`],
    ["MsgAddOpinion", (modid: string, what: string, whom: string) => `Gain opinion modifier ${textInQuotes(what)} <!-- ${modid} --> towards ${whom}`],
    ["MsgNewHeir", () => "Gain a new heir"],
    ["MsgNewHeirClaim", (claim: string) => `Gain a new heir with claim strength ${claim}`],
    ["MsgNewHeirDynasty", (flag: string) => `Gain a new heir of the same dynasty as ${flag}`],
    ["MsgNewHeirDynastyClaim", (claim: string) => `Gain a new heir with claim strength ${claim}`],
    ["MsgNewHeirAge", (age: string) => `Gain a new ${age} year old heir`],
    ["MsgNewHeirAgeClaim", (age: string, claim: string) => `Gain a new ${age} year old heir with claim strength ${claim}`],
    ["MsgNewHeirAgeFlag", (age: string, flag: string) => `Gain a new ${age} year old heir of the same dynasty as ${flag}`],
    ["MsgNewHeirAgeFlagClaim", (age: string, flag: string, claim: string) => `Gain a new ${age} year old heir of the same dynasty as ${flag} with claim strength ${claim}`],
    ["MsgBuildToForcelimitLand", (inficon: string, infantry: string, cavicon: string, cavalry: string, articon: string, artillery: string) => `Build land units to forcelimit: ${inficon} ${numberToPercentage(infantry)} infantry, ${cavicon} ${numberToPercentage(cavalry)} cavalry, ${articon} ${numberToPercentage(artillery)} artillery`],
    ["MsgBuildToForcelimitNavy", (heavyicon: string, heavy: string, lighticon: string, light: string, gallicon: string, galley: string, transpicon: string, transport: string) => `Build naval units to forcelimit: ${heavyicon} ${numberToPercentage(heavy)} heavy ships, ${lighticon} ${numberToPercentage(light)} light ships, ${gallicon} ${numberToPercentage(galley)} galleys, ${transpicon} ${numberToPercentage(transport)} transports`],
    ["MsgProvinceEvent", () => "province event"],
    ["MsgCountryEvent", () => "country event"],
    ["MsgTriggerEvent", (evttype: string, evtid: string, name: string) => `Trigger ${evttype} ${textInQuotes(name)} <!-- ${evtid} -->`],
    ["MsgTriggerEventDays", (evttype: string, evtid: string, name: string, days: string) => `Trigger ${evttype} ${textInQuotes(name)} <!-- ${evtid} --> in ${days} days`],
    ["MsgDeclareWarWithCB", (whom: string, cbtype: string) => `Declare war on ${whom} using ${cbtype} casus belli`],
    ["MsgGainAdvisor", (skill: string) => `Gain skill ${skill} advisor`],
    ["MsgGainAdvisorDiscount", (skill: string) => `Gain skill ${skill} advisor (50% cheaper to employ)`],
    ["MsgGainAdvisorLoc", (where: string, skill: string) => `Gain skill ${skill} advisor in ${where}`],
    ["MsgGainAdvisorLocDiscount", (where: string, skill: string) => `Gain skill ${skill} advisor in ${where} (50% cheaper to employ)`],
    ["MsgGainAdvisorName", (name: string, skill: string) => `Gain skill ${skill} advisor named ${name}`],
    ["MsgGainAdvisorNameDiscount", (name: string, skill: string) => `Gain skill ${skill} advisor named ${name} (50% cheaper to employ)`],
    ["MsgGainAdvisorNameLoc", (name: string, where: string, skill: string) => `Gain skill ${skill} advisor named ${name} in ${where}`],
    ["MsgGainAdvisorNameLocDiscount", (name: string, where: string, skill: string) => `Gain skill ${skill} advisor named ${name} in ${where} (50% cheaper to employ)`],
    ["MsgGainAdvisorType", (advtype: string, skill: string) => `Gain skill ${skill} ${advtype} advisor`],
    ["MsgGainAdvisorTypeDiscount", (advtype: string, skill: string) => `Gain skill ${skill} ${advtype} advisor (50% cheaper to employ)`],
    ["MsgGainAdvisorTypeLoc", (advtype: string, where: string, skill: string) => `Gain skill ${skill} ${advtype} advisor in ${where}`],
    ["MsgGainAdvisorTypeLocDiscount", (advtype: string, where: string, skill: string) => `Gain skill ${skill} ${advtype} advisor in ${where} (50% cheaper to employ)`],
    ["MsgGainAdvisorTypeName", (advtype: string, name: string, skill: string) => `Gain skill ${skill} ${advtype} advisor named ${name}`],
    ["MsgGainAdvisorTypeNameDiscount", (advtype: string, name: string, skill: string) => `Gain skill ${skill} ${advtype} advisor named ${name} (50% cheaper to employ)`],
    ["MsgGainAdvisorTypeNameLoc", (advtype: string, name: string, where: string, skill: string) => `Gain skill ${skill} ${advtype} advisor named ${name} in ${where}`],
    ["MsgGainAdvisorTypeNameLocDiscount", (advtype: string, name: string, where: string, skill: string) => `Gain skill ${skill} ${advtype} advisor named ${name} in ${where} (50% cheaper to employ)`],
    ["MsgGainFemaleAdvisor", (female: boolean, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor`],
    ["MsgGainFemaleAdvisorDiscount", (female: boolean, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor (50% cheaper to employ)`],
    ["MsgGainFemaleAdvisorLoc", (female: boolean, where: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor in ${where}`],
    ["MsgGainFemaleAdvisorLocDiscount", (female: boolean, where: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor in ${where} (50% cheaper to employ)`],
    ["MsgGainFemaleAdvisorName", (female: boolean, name: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor named ${name}`],
    ["MsgGainFemaleAdvisorNameDiscount", (female: boolean, name: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor named ${name} (50% cheaper to employ)`],
    ["MsgGainFemaleAdvisorNameLoc", (female: boolean, name: string, where: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor named ${name} in ${where}`],
    ["MsgGainFemaleAdvisorNameLocDiscount", (female: boolean, name: string, where: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} advisor named ${name} in ${where} (50% cheaper to employ)`],
    ["MsgGainFemaleAdvisorType", (female: boolean, advtype: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} ${advtype} advisor`],
    ["MsgGainFemaleAdvisorTypeDiscount", (female: boolean, advtype: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} ${advtype} advisor (50% cheaper to employ)`],
    ["MsgGainFemaleAdvisorTypeLoc", (female: boolean, advtype: string, where: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} ${advtype} advisor in ${where}`],
    ["MsgGainFemaleAdvisorTypeLocDiscount", (female: boolean, advtype: string, where: string, skill: string) => `Gain skill ${skill} ${ifElseThen(female, "female", "male")} ${advtype} advisor in ${where} (50% cheaper to employ)`],

    ["MsgGainFemaleAdvisorTypeName", (female: string, advtype: string, name: string, skill: string) => 
        `Gain skill ${skill} ${female ? "female" : "male"} ${advtype} advisor named ${name}`
    ],
    ["MsgGainFemaleAdvisorTypeNameDiscount", (female: string, advtype: string, name: string, skill: string) => 
        `Gain skill ${skill} ${female ? "female" : "male"} ${advtype} advisor named ${name} (50% cheaper to employ)`
    ],
    ["MsgGainFemaleAdvisorTypeNameLoc", (female: string, advtype: string, name: string, where: string, skill: string) => 
        `Gain skill ${skill} ${female ? "female" : "male"} ${advtype} advisor named ${name} in ${where}`
    ],
    ["MsgGainFemaleAdvisorTypeNameLocDiscount", (female: string, advtype: string, name: string, where: string, skill: string) => 
        `Gain skill ${skill} ${female ? "female" : "male"} ${advtype} advisor named ${name} in ${where} (50% cheaper to employ)`
    ],
    ["MsgRebelLeaderRuler", () => "The leader of the rebels becomes the country's new ruler"],
    ["MsgNewRuler", (regent: string) => `A new ${regent ? "regent" : "ruler"} comes to power`],
    ["MsgNewRulerLeader", (regent: string, name: string) => `The leader ${name} becomes ${regent ? "regent" : "ruler"}`],
    ["MsgNewRulerAttribs", (regent: string) => `A new ${regent ? "regent" : "ruler"} comes to power with the following attributes:`],
    ["MsgNewRulerLeaderAttribs", (regent: string, name: string) => `The leader ${name} becomes ${regent ? "regent" : "ruler"} with the following attributes:`],
    ["MsgLeaderRuler", (regent: string, name: string) => `The leader ${name} comes to power as ${regent ? "regent" : "ruler"}`],
    ["MsgNewRulerName", (name: string) => `Named ${name}`],
    ["MsgNewRulerDynasty", (name: string) => `Of the ${name} dynasty`],
    ["MsgNewRulerDynastyAs", (name: string) => `Of the same dynasty as ${name}`],
    ["MsgNewRulerOriginalDynasty", () => "Of the country's original dynasty"],
    ["MsgNewRulerHistoricDynasty", () => "Of one of the country's historic dynasties"],
    ["MsgNewRulerAge", (amount: string) => `Aged ${amount} years`],
    ["MsgNewRulerAdm", (fixed: string, amount: string) => `${fixed ? "Fixed " : ""}{{icon|adm}} ${amount} administrative skill`],
    ["MsgNewRulerDip", (fixed: string, amount: string) => `${fixed ? "Fixed " : ""}{{icon|dip}} ${amount} diplomatic skill`],
    ["MsgNewRulerMil", (fixed: string, amount: string) => `${fixed ? "Fixed " : ""}{{icon|mil}} ${amount} military skill`],
    ["MsgNewRulerClaim", (amount: string) => `Claim strength ${amount}`],
    ["MsgNewRulerFixed", (adm: string, dip: string, mil: string) => 
        `A new ruler comes to power with fixed skills {{icon|adm}} ${adm}, {{icon|dip}} ${dip}, {{icon|mil}} ${mil}`
    ],
    ["MsgEstateHasInfluenceModifier", (icon: string, estate: string, modifier: string) => 
        `${icon} ${estate} estate has influence modifier ${textInQuotes(modifier)}`
    ],
    ["MsgTriggerSwitch", () => "The first of the following that is true:"],
    ["MsgTriggerSwitchClause", (cond: string) => `If ${cond}:`],
    ["MsgProvinceHasRebels", (icon: string, rtype: string) => `Province's most likely rebel type is ${icon} ${rtype}`],
    ["MsgRebelsFriendlyTo", (friend: string) => `friendly to ${friend}`],
    ["MsgRebelsLedBy", (leader: string) => `led by ${leader}`],
    ["MsgRebelsGainProgress", (amount: string) => `gaining ${amount} progress towards their next uprising`],
    ["MsgSpawnRebels", (rtype: string, size: string, friend: string, leader: string, win: string, progress: string) => 
        `${rtype} (size ${size})${friend} rise in revolt${leader}${win ? " and occupy the province" : ""}${progress}`
    ],
    ["MsgRebelsHaveRisen", (icon: string, rtype: string) => `${icon} ${rtype} have risen in revolt`],
    ["MsgTagGainsCore", (who: string) => `${who} gains a core on this province`],
    ["MsgGainCoreOnProvince", (prov: string) => `Gain core on ${prov}`],
    ["MsgHasDLC", (icon: string, dlc: string) => `DLC ${icon} ${dlc} is active`],
    ["MsgProvince", (where: string) => `Province ${where}:`],
    ["MsgTechGroup", (icon: string, name: string) => `Technology group is ${icon} ${name}`],
    ["MsgNumOfReligion", (icon: string, name: string, amount: string) => 
        `Has at least ${amount} ${pluralOrSingle(amount, "province", "provinces")} of ${icon} ${name} religion`
    ],
    ["MsgIsStrongestTradePower", (who: string) => `${who} is the strongest trade power in this node`],
    ["MsgAreaIs", (what: string) => `Is in ${what} area`],
    ["MsgAreaIsAs", (what: string) => `Is in the same area as ${what}`],
    ["MsgDominantReligion", (icon: string, what: string) => `The country's dominant religion is ${icon} ${what}`],
    ["MsgDominantReligionAs", (whom: string) => `The country's dominant religion is that of ${whom}`],
    ["MsgEnableReligion", (icon: string, what: string) => `Enable the ${icon} ${what} religion`],
    ["MsgHREReligion", (icon: string, what: string) => `The Holy Roman Empire's official religion is ${icon} ${what}`],
    ["MsgSetHREReligionLocked", (yn: string) => `The Holy Roman Empire's religion ${yn ? "becomes fixed" : "is no longer fixed"}`],
    ["MsgSetHREReligion", (icon: string, what: string) => `The Holy Roman Empire's official religion becomes ${icon} ${what}`],
    ["MsgSetHREHereticReligion", (icon: string, what: string) => `The ${icon} ${what} religion is considered heretical within the Holy Roman Empire`],
    ["MsgSignWestphalia", () => `From now on, the Emperor, Electors, and Princes of the {{icon|hre}} Holy Roman Empire may be of any Christian religion without being considered heretics.`],
    ["MsgHRELeaguesEnabled", (yn: string) => `Leagues for the religion of the Holy Roman Empire ${yn ? "have" : "have ''not''"} begun to form`],
    ["MsgHREReligionLocked", (yn: string) => `The religion of the Holy Roman Empire ${yn ? "is" : "is ''not''"} fixed`],
    ["MsgHREWestphalia", (yn: string) => `The Peace of Westphalia ${yn ? "has" : "has ''not''"} been signed`],
    ["MsgIsElector", (yn: string) => `Is${yn ? "" : " ''not''"} an Elector of the Holy Roman Empire`],
    ["MsgNoHREReforms", () => `No reforms have been passed in the Holy Roman Empire`],
    ["MsgHREPassedReform", (what: string) => `The imperial reform ''${what}'' has been passed`],
    ["MsgEnableHRELeagues", () => `Leagues for the religion of the Holy Roman Empire begin to form.`],
    ["MsgIsInLeagueWar", (yn: string) => `Is${yn ? "" : " ''not''"} involved in a religious league war`],
    ["MsgIsLeagueEnemy", (whom: string) => `Is in the opposite religious league to ${whom}`],
    ["MsgReligionYears", (icon: string, name: string, years: string) => `The ${icon} ${name} religion has existed for at least ${years} years`],
    ["MsgHasIdea", (what: string) => `Has idea "${what}"`],
    ["MsgReligionProvinces", (icon: string, name: string, amount: string) => `Country has at least ${amount} ${pluralOrSingle(amount, "province", "provinces")} following the ${icon} ${name} religion`],
    ["MsgGoodsProvinces", (icon: string, name: string, amount: string) => `Country has at least ${amount} ${pluralOrSingle(amount, "province", "provinces")} producing ${icon} ${name}`],
    ["MsgHasAristocraticIdea", (name: string, num: string) => `Has {{icon|aristocratic}} Aristocratic idea ${num} "${name}"`],
    ["MsgHasEconomicIdea", (name: string, num: string) => `Has {{icon|economic}} Economic idea ${num} "${name}"`],
    ["MsgHasDefensiveIdea", (name: string, num: string) => `Has {{icon|defensive}} Defensive idea ${num} "${name}"`],
    ["MsgHasInnovativeIdea", (name: string, num: string) => `Has {{icon|innovative}} Innovative idea ${num} "${name}"`],
    ["MsgHasOffensiveIdea", (name: string, num: string) => `Has {{icon|offensive}} Offensive idea ${num} "${name}"`],
    ["MsgHasMaritimeIdea", (name: string, num: string) => `Has {{icon|maritime}} Maritime idea ${num} "${name}"`],
    ["MsgColonists", (icon: string, amount: string) => `${icon} ${amount} Colonists`],
    ["MsgMayExplore", () => `{{icon|may explore|28px}} Can recruit explorers and conquistadors. Explorers may explore ocean provinces.`],
    ["MsgGainColonialRange", (icon: string, amount: string) => `${icon} ${amount} Colonial range`],
    ["MsgSettlerChance", (icon: string, amount: string) => `${icon} ${amount} Settler chance`],
    ["MsgGlobalSettlers", (icon: string, amount: string) => `${icon} ${amount} Global settler increase`],
    ["MsgGlobalTariffs", (icon: string, amount: string) => `${icon} ${amount} Global tariffs`],
    ["MsgNavalForcelimitMod", (icon: string, amount: string) => `${icon} ${amount} Naval forcelimit modifier`],
    ["MsgGainOverseasCB", () => `Gain permanent "Overseas Expansion" [[Casus Belli]] against countries with Indian, Sub-Saharan, Chinese, or Nomad tech group.`],
    ["MsgGainPrimitivesCB", () => `Gain permanent "Colonial Conquest" [[Casus Belli]] against all primitives.`],
    ["MsgNavyTradition", (icon: string, amount: string) => `${icon} Naval tradition is at least ${amount}`],
    ["MsgYearlyNavyTradition", (icon: string, amount: string) => `${icon} ${amount} Yearly naval tradition`],
    ["MsgHeavyShipCombatAbility", (icon: string, amount: string) => `${icon} ${amount} Heavy ship combat ability`],
    ["MsgLightShipCombatAbility", (icon: string, amount: string) => `${icon} ${amount} Light ship combat ability`],
    ["MsgGalleyCombatAbility", (icon: string, amount: string) => `${icon} ${amount} Galley combat ability`],
    ["MsgGlobalShipRepair", (icon: string, amount: string) => `${icon} ${amount} Ship repair`],
    ["MsgGlobalShipCost", (icon: string, amount: string) => `${icon} ${amount} Ship cost`],
    ["MsgRegimentCost", (icon: string, amount: string) => `${icon} ${amount} Regiment cost`],
    ["MsgNavalLeaderManeuver", (icon: string, amount: string) => `${icon} ${amount} Naval leader maneuver`],
    ["MsgBlockadeEfficiency", (icon: string, amount: string) => `${icon} ${amount} Blockade efficiency`],
    ["MsgGainSeaRepair", () => `Ships repair while in coastal sea provinces.`],
    ["MsgPrimitives", (yn: string) => `Is${yn ? "" : " ''not''"} primitive`],
    ["MsgGlobalTaxModifier", (icon: string, amount: string) => `${icon} ${amount} National tax modifier`],
    ["MsgBuildCost", (icon: string, amount: string) => `${icon} ${amount} Construction cost`],
    ["MsgYearlyInflationReduction", (icon: string, amount: string) => `${icon} ${amount} Yearly inflation reduction`],
    ["MsgInterestPerAnnum", (icon: string, amount: string) => `${icon} ${amount} Interest per annum`],
    ["MsgGlobalAutonomy", (icon: string, amount: string) => `${icon} ${amount} Monthly autonomy change`],
    ["MsgLandMaintenanceMod", (icon: string, amount: string) => `${icon} ${amount} Land maintenance modifier`],
    ["MsgNavalMaintenanceMod", (icon: string, amount: string) => `${icon} ${amount} Naval maintenance modifier`],
    ["MsgProdEff", (icon: string, amount: string) => `${icon} Production efficiency is at least ${amount}`],
    ["MsgProdEffBonus", (icon: string, amount: string) => `${icon} ${amount} Production efficiency`],
    ["MsgDevelCost", (icon: string, amount: string) => `${icon} Development cost ${amount}`],
    ["MsgLocalDevelopmentCost", (yn: string, icon: string, amount: string) => `${icon} Local development cost ${amount}${yn ? "" : " (replace=no)"}`],
    

    ["MsgGainReligiousCB", () => `{{icon|cb on religious enemies|28px}} Gain permanent "Holy War" and "Purging of Heresy" Casus Belli against heathens and heretics respectively.`],
    ["MsgMissionaries", (icon: string, amount: string) => `${icon} ${amount} Missionaries`],
    ["MsgMissionaryMaintenanceCost", (icon: string, amount: string) => `${icon} ${amount} Missionary Maintenance Cost`],
    ["MsgStabilityCost", (icon: string, amount: string) => `${icon} ${amount} Stability cost modifier`],
    ["MsgMissionaryStrength", (icon: string, amount: string) => `${icon} ${amount} Missionary strength`],
    ["MsgToleranceHeathen", (icon: string, amount: string) => `${icon} ${amount} Tolerance of heathens`],
    ["MsgToleranceHeretic", (icon: string, amount: string) => `${icon} ${amount} Tolerance of heretics`],
    ["MsgToleranceTrue", (icon: string, amount: string) => `${icon} ${amount} Tolerance of the true faith`],
    ["MsgPapalInfluence", (icon: string, amount: string) => `${icon} Papal influence is at least ${amount}`],
    ["MsgYearlyPapalInfluence", (icon: string, amount: string) => `${icon} ${amount} Yearly papal influence`],
    ["MsgYearlyDevotion", (icon: string, amount: string) => `${icon} ${amount} Yearly devotion`],
    ["MsgMonthlyFervor", (icon: string, amount: string) => `${icon} ${amount} Monthly fervor`],
    ["MsgChurchPowerModifier", (icon: string, amount: string) => `${icon} ${amount} Church power`],
    ["MsgPrestige", (icon: string, amount: string) => `${icon} Prestige is at least ${amount}`],
    ["MsgYearlyPrestige", (icon: string, amount: string) => `${icon} ${amount} Yearly prestige`],
    ["MsgMissionaryStrengthVsHeretics", (icon: string, amount: string) => `${icon} ${amount} Missionary strength vs heretics`],
    ["MsgCultureConvCost", (icon: string, amount: string) => `${icon} ${amount} Culture conversion cost`],
    ["MsgHasOpinion", (amount: string, whom: string) => `Opinion of ${whom} is at least ${amount}`],
    ["MsgNormalOrHistoricalNations", (yn: string) => `${yn ? "Playing" : "Not playing"} with normal or historical nations`],
    ["MsgIsCustomNation", (yn: string) => `Is${yn ? "" : " not"} playing a custom nation`],
    ["MsgReligionEnabled", (icon: string, what: string) => `The ${icon} ${what} religion is enabled`],
    ["MsgCapitalIs", (what: string) => `Capital is ${what}`],
    ["MsgFullIdeaGroup", (icon: string, what: string) => `Has completed ${icon} ${what}`],
    ["MsgTradeIncomePercentage", (amount: string) => `Trade accounts for at least ${amount} of national income`],
    ["MsgReligiousUnity", (icon: string, amount: string) => `${icon} Religious unity is at least ${amount}`],
    ["MsgHasADM", (icon: string, amount: string) => `Has at least ${icon} ${amount} administrative power`],
    ["MsgHasDIP", (icon: string, amount: string) => `Has at least ${icon} ${amount} diplomatic power`],
    ["MsgHasMIL", (icon: string, amount: string) => `Has at least ${icon} ${amount} military power`],
    ["MsgRankDuchy", () => "Government rank is at least Duchy"],
    ["MsgRankKingdom", () => "Government rank is Kingdom or Empire"],
    ["MsgRankEmpire", () => "Government rank is Empire"],
    ["MsgSetRankDuchy", () => "Set government rank to Duchy"],
    ["MsgSetRankKingdom", () => "Set government rank to Kingdom"],
    ["MsgSetRankEmpire", () => "Set government rank to Empire"],
    ["MsgOverextension", (icon: string, amount: string) => `${icon} Overextension is at least ${amount}`],
    ["MsgRandomNewWorld", (yn: string) => `Is${yn ? "" : " not"} playing with a Random New World`],
    ["MsgIsColonialNation", (yn: string) => `Is${yn ? "" : " not"} a colonial nation`],
    ["MsgIsFormerColonialNation", (yn: string) => `Is${yn ? "" : " not"} a former colonial nation`],
    ["MsgIsFreeOrTributaryTrigger", (yn: string) => `Is${yn ? "" : " neither"} independent or a tributary`],
    ["MsgIsNomad", (yn: string) => `Is${yn ? "" : " not"} a steppe horde`],
    ["MsgReligionReformed", (yn: string) => `The country's religion has${yn ? "" : " not"} been reformed`],
    ["MsgChangeTag", (who: string) => `Country becomes ${who}`],
    ["MsgSetInEmpire", (yn: string) => `Province ${yn ? "joins" : "leaves"} the Holy Roman Empire`],
    ["MsgHasSecondaryReligion", (yn: string) => `${yn ? "Has" : "Does not have"} a secondary religion`],
    ["MsgSecondaryReligion", (icon: string, what: string) => `Secondary religion is ${icon} ${what}`],
    ["MsgIsDefenderOfFaith", (yn: string) => `Is${yn ? "" : " not"} Defender of the Faith`],
    ["MsgLegitimacyOrHordeUnity", (amount: string) => `Legitimacy or Horde unity is at least ${amount}`],
    ["MsgCheckVariable", (what: string, amount: string) => `Value of variable ${what} is at least ${amount}`],
    ["MsgChangeTechGroup", (icon: string, what: string) => `Change technology group to ${icon} ${what}`],
    ["MsgChangeUnitType", (icon: string, what: string) => `Change units to ${icon} ${what}`],
    ["MsgNoBaseWeight", () => "(no base weight?)"],
    ["MsgAIBaseWeight", (amount: string) => `Base weight: ${amount}`],
    ["MsgAIFactorOneline", (factor: string, multiplier: string) => `${factor}: ${multiplier}`],
    ["MsgAIFactorHeader", (multiplier: string) => `${multiplier}:`],
    ["MsgLucky", (yn: string) => `Is${yn ? "" : " not"} a lucky nation`],
    ["MsgHasAdvisorLevel", (icon: string, what: string, level: string) => `Has a level ${level} ${icon} ${what} advisor`],
    ["MsgNumRoyalMarriages", (icon: string, amount: string) => `Has at least ${icon} ${amount} royal ${pluralOrSingle(amount, "marriage", "marriages")}`],
    ["MsgIsBankrupt", (yn: string) => `Is${yn ? "" : " not"} bankrupt`],
    ["MsgNumColonialSubjects", (amount: string) => `Has at least ${amount} colonial ${pluralOrSingle(amount, "subject", "subjects")}`],
    ["MsgTradeEfficiency", (icon: string, amount: string) => `${icon} Trade efficiency is at least ${amount}`],
    ["MsgTradeEfficiencyBonus", (icon: string, amount: string) => `${icon} ${amount} Trade efficiency`],
    ["MsgHasWarTaxes", (yn: string) => `Has${yn ? "" : " not"} raised war taxes`],
    ["MsgRevoltPercentage", (amount: string) => `At least ${amount} of provinces are in revolt`],
    ["MsgHasAnyDisaster", (yn: string) => `${yn ? "Has" : "Does not have"} an ongoing disaster`],
    ["MsgHasActivePolicy", (what: string) => `Has enacted the policy "${what}"`],
    ["MsgHasDucats", (icon: string, amount: string) => `Has at least ${icon} ${amount} ducats`],
    ["MsgHasParliament", (yn: string) => `The country ${yn ? "has" : "does not have"} a parliament`],

    ["MsgHasTruce", (yn: string) => `The country ${yn === "yes" ? "has" : "does not have"} a truce with another country`],
    ["MsgNumRebelControlledProvinces", (amount: string) => `At least ${amount} provinces are controlled by rebels`],
    ["MsgFortLevel", (icon: string, amount: string) => `${icon} Fort level is at least ${amount}`],
    ["MsgHasTradeModifier", (who: string, what: string) => `${who} has trade modifier ${what}`],
    ["MsgIsMonth", (what: string) => `Month is ${what}`],
    ["MsgIsSea", (yn: string) => `Is${yn ? "" : " not"} sea`],
    ["MsgHeavyShip", (whom: string) => `Create a {{icon|heavy ship}} heavy ship belonging to ${whom}`],
    ["MsgLightShip", (whom: string) => `Create a {{icon|light ship}} light ship belonging to ${whom}`],
    ["MsgGalley", (whom: string) => `Create a {{icon|galley}} galley belonging to ${whom}`],
    ["MsgHasMerchant", (who: string) => `${who} has a merchant present`],
    ["MsgNumColonies", (amount: string) => `Has at least ${amount} colonies`],
    ["MsgChangeCulture", (what: string) => `Change culture to ${what}`],
    ["MsgChangeSameCulture", (whom: string) => `Change culture to that of ${whom}`],
    ["MsgNavalForcelimit", (icon: string, amount: string) => `${icon} Naval forcelimit is at least ${amount}`],
    ["MsgBlockade", (icon: string, amount: string) => `Is at least ${icon} ${amount} blockaded`],
    ["MsgCreateAlliance", (whom: string) => `Create alliance with ${whom}`],
    ["MsgAddLocalUnrest", (icon: string, amount: string) => `${amount} ${icon} ${amount} unrest`],
    ["MsgGoldIncomePercentage", (icon: string, amount: string) => `At least ${amount}% of the country's income is from ${icon} Gold`],
    ["MsgIsTribal", (yn: string) => `Is${yn ? "" : " not"} tribal`],
    ["MsgSetCapital", (what: string) => `Change capital to ${what}`],
    ["MsgChangePrimaryCulture", (what: string) => `Change primary culture to ${what}`],
    ["MsgColonialRegion", (where: string) => `Is in colonial region ${where}`],
    ["MsgJuniorUnionWith", (whom: string) => `Is the junior partner in a personal union with ${whom}`],
    ["MsgSeniorUnionWith", (whom: string) => `Is the senior partner in a personal union with ${whom}`],
    ["MsgVassalOf", (whom: string) => `Is a vassal of ${whom}`],
    ["MsgOverlordOf", (whom: string) => `Is the overlord of ${whom}`],
    ["MsgChangeProvinceName", (what: string) => `Rename province to ${what}`],
    ["MsgRenameCapital", (what: string) => `Rename provincial capital to ${what}`],
    ["MsgOwnsOrVassal", (where: string) => `Owns ${where} or is overlord of its owner`],
    ["MsgIsInColonialRange", (whom: string) => `Is within colonial range of ${whom}`],
    ["MsgConstructingGreatProject", (what: string) => `Is constructing the ${what}`],
    ["MsgConstructing", (what: string) => `Is constructing a ${what}`],
    ["MsgStartConstructingGreatProject", (what: string) => `Begin constructing the ${what}`],
    ["MsgCancelConstruction", () => `Cancel construction`],
    ["MsgYearsOfIncome", (icon: string, amount: string) => `Treasury contains at least ${icon} ${amount} years' worth of income`],
    ["MsgLibertyDesire", (icon: string, amount: string) => `${icon} Liberty desire is at least ${amount}`],
    ["MsgGainLibertyDesire", (icon: string, amount: string) => `Gain ${icon} ${amount} liberty desire`],
    ["MsgColonialParent", () => `This country's colonial parent:`],
    ["MsgAlways", (yn: string) => `${yn ? "{{icon|yes}} Always" : "{{icon|no}} Never"}`],
    ["MsgCapitalCultureDominant", () => `The capital's {{icon|culture}} culture is dominant in the country`],
    ["MsgNumUnions", (icon: string, amount: string) => `Has at least ${icon} ${amount} personal unions`],
    ["MsgNumVassals", (icon: string, amount: string) => `Has at least ${icon} ${amount} vassals`],
    ["MsgFreeVassal", (whom: string) => `Release vassal ${whom} as an independent country`],
    ["MsgHasMissionary", (yn: string) => `${yn ? "Has" : "Does not have"} an active missionary`],
    ["MsgNavyPercentage", (icon: string, amount: string) => `Navy is at least ${icon} ${amount}% of force limit`],
    ["MsgWasForceConverted", (yn: string) => `Was${yn ? "" : " not"} force converted`],
    ["MsgFemaleEmperorAllowed", (yn: string) => `The Emperor may${yn ? "" : " not"} be female`],
    ["MsgImperialAuthority", (icon: string, amount: string) => `${icon} Imperial Authority is at least ${amount}`],
    ["MsgHasFemaleHeir", (yn: string) => `${yn ? "Has" : "Does not have"} a female heir`],
    ["MsgPiety", (icon: string, amount: string) => `${icon} Piety is at least ${amount}`],
    ["MsgIsInTutorial", (yn: string) => `Is${yn ? "" : " not"} in the tutorial`],
    ["MsgGainFervor", (icon: string, amount: string) => `Gain ${icon} ${amount} fervor`],
    ["MsgGainChurchPower", (icon: string, amount: string) => `Gain ${icon} ${amount} church power`],
    ["MsgIncomeFromVassals", (icon: string, amount: string) => `${icon} ${amount}% Income from vassals`],
    ["MsgCostToFabricateClaims", (icon: string, amount: string) => `${icon} ${amount}% Cost to fabricate claims`],
    ["MsgTimeToFabricateClaims", (icon: string, amount: string) => `${icon} ${amount}% Time to fabricate claims`],
    ["MsgDiploAnnexCost", (icon: string, amount: string) => `${icon} ${amount}% Diplomatic annexation cost`],
    ["MsgAEImpact", (icon: string, amount: string) => `${icon} ${amount}% Aggressive expansion impact`],
    ["MsgDiploRep", (icon: string, amount: string) => `${icon} ${amount} Diplomatic reputation`],
    ["MsgEnvoyTravelTime", (icon: string, amount: string) => `${icon} ${amount}% Envoy travel time`],
    ["MsgDiploRelations", (icon: string, amount: string) => `${icon} ${amount} Diplomatic relations`],
    ["MsgVassalForcelimitContribution", (icon: string, amount: string) => `${icon} ${amount} Vassal force limit contribution`],
    ["MsgUnjustifiedDemands", (icon: string, amount: string) => `${icon} ${amount}% Unjustified demands`],
    ["MsgInfantryCombatAbility", (icon: string, amount: string) => `${icon} ${amount}% Infantry combat ability`],
    ["MsgCavalryCombatAbility", (icon: string, amount: string) => `${icon} ${amount}% Cavalry combat ability`],
    ["MsgArtilleryCombatAbility", (icon: string, amount: string) => `${icon} ${amount}% Artillery combat ability`],
    ["MsgShipDurability", (icon: string, amount: string) => `${icon} ${amount}% Ship durability`],
    ["MsgMoraleOfArmies", (icon: string, amount: string) => `${icon} ${amount}% Morale of armies`],

    ["MsgMoraleOfNavies", (icon: string, amount: string) => `${icon} ${amount} Morale of navies`],
    ["MsgNavalAttrition", (icon: string, amount: string) => `${icon} ${amount}% Naval attrition`],
    ["MsgDiscipline", (icon: string, amount: string) => `${icon} ${amount}% Discipline`],
    ["MsgNationalManpowerMod", (icon: string, amount: string) => `${icon} ${amount} National manpower modifier`],
    ["MsgManpowerRecoverySpeed", (icon: string, amount: string) => `${icon} ${amount} Manpower recovery speed`],
    ["MsgAvailableMercs", (icon: string, amount: string) => `${icon} ${amount}% Available mercenaries`],
    ["MsgGarrisonSize", (icon: string, amount: string) => `${icon} ${amount}% Garrison size`],
    ["MsgLandAttrition", (icon: string, amount: string) => `${icon} ${amount}% Land attrition`],
    ["MsgLandForcelimitMod", (icon: string, amount: string) => `${icon} ${amount}% Land force limit modifier`],
    ["MsgPrestigeDecay", (icon: string, amount: string) => `${icon} ${amount}% Prestige decay`],
    ["MsgMercCost", (icon: string, amount: string) => `${icon} ${amount}% Mercenary cost`],
    ["MsgTechCost", (icon: string, amount: string) => `${icon} ${amount}% Technology cost`],
    ["MsgPossibleAdvisors", (icon: string, amount: string) => `${icon} ${amount} Possible advisors`],
    ["MsgReduceInflationCost", (icon: string, amount: string) => `${icon} ${amount}% Reduce inflation cost`],
    ["MsgLeadersWithoutUpkeep", (icon: string, amount: string) => `${icon} ${amount} Leader(s) without upkeep`],
    ["MsgAdvisorCost", (icon: string, amount: string) => `${icon} ${amount}% Advisor costs`],
    ["MsgCoreCreationCost", (icon: string, amount: string) => `${icon} ${amount}% Core creation cost`],
    ["MsgMercMaintenance", (icon: string, amount: string) => `${icon} ${amount}% Mercenary maintenance modifier`],
    ["MsgADMTechCost", (icon: string, amount: string) => `${icon} ${amount}% Administrative technology cost`],
    ["MsgDIPTechCost", (icon: string, amount: string) => `${icon} ${amount}% Diplomatic technology cost`],
    ["MsgGoodsProducedMod", (icon: string, amount: string) => `${icon} ${amount}% Goods produced modifier`],
    ["MsgNavalLeaderFire", (icon: string, amount: string) => `${icon} ${amount} Naval leader fire`],
    ["MsgNavalLeaderShock", (icon: string, amount: string) => `${icon} ${amount} Naval leader shock`],
    ["MsgPrestigeFromLand", (icon: string, amount: string) => `${icon} ${amount}% Prestige from land battles`],
    ["MsgPrestigeFromNaval", (icon: string, amount: string) => `${icon} ${amount}% Prestige from naval battles`],
    ["MsgDiplomats", (icon: string, amount: string) => `${icon} ${amount} Diplomats`],
    ["MsgWarExhaustionCost", (icon: string, amount: string) => `${icon} ${amount}% Cost of reducing war exhaustion`],
    ["MsgImproveRelations", (icon: string, amount: string) => `${icon} ${amount}% Improve relations`],
    ["MsgProvinceWarscoreCost", (icon: string, amount: string) => `${icon} ${amount}% Province warscore cost`],
    ["MsgReducedStabImpacts", () => "Lowered impact on stability from diplomatic actions"],
    ["MsgNationalUnrest", (icon: string, amount: string) => `${icon} ${amount}% National unrest`],
    ["MsgYearsOfSeparatism", (icon: string, amount: string) => `${icon} ${amount} Years of separatism`],
    ["MsgAccCultureThreshold", (icon: string, amount: string) => `${icon} ${amount}% Accepted culture threshold`],
    ["MsgBetterRelationsOverTime", (icon: string, amount: string) => `${icon} ${amount}% Better relations over time`],
    ["MsgIdeaCost", (icon: string, amount: string) => `${icon} ${amount}% Idea cost`],
    ["MsgMerchants", (icon: string, amount: string) => `${icon} ${amount} Merchants`],
    ["MsgRecruitmentTime", (icon: string, amount: string) => `${icon} ${amount}% Recruitment time`],
    ["MsgShipbuildingTime", (icon: string, amount: string) => `${icon} ${amount}% Shipbuilding time`],
    ["MsgGlobalTradePower", (icon: string, amount: string) => `${icon} ${amount}% Global trade power`],
    ["MsgEmbargoEff", (icon: string, amount: string) => `${icon} ${amount}% Embargo efficiency`],
    ["MsgPrivateerEff", (icon: string, amount: string) => `${icon} ${amount}% Privateer efficiency`],
    ["MsgGlobalSpyDefence", (icon: string, amount: string) => `${icon} ${amount}% National spy defence`],
    ["MsgMaySabotageReputation", () => "{{icon|may sabotage reputation|28px}} May [[sabotage reputation]]"],
    ["MsgSpyOffense", (icon: string, amount: string) => `${icon} ${amount}% Spy offense`],
    ["MsgCovertActionRelationImpact", (icon: string, amount: string) => `${icon} ${amount}% Covert action relation impact`],
    ["MsgMayStudyTech", () => "{{icon|may study technology|28px}} May [[study technology]]"],
    ["MsgMaySowDiscontent", () => "{{icon|may sow discontent|28px}} May [[sow discontent]]"],
    ["MsgMayAgitateForLiberty", () => "May [[agitate for liberty]]"],
    ["MsgMayInfiltrateAdministration", () => "{{icon|may infiltrate administration|28px}} May [[infiltrate administration]]"],
    ["MsgRebelSupportEff", (icon: string, amount: string) => `${icon} ${amount}% Rebel support efficiency`],
    ["MsgArmyTraditionDecay", (icon: string, amount: string) => `${icon} ${amount}% Army tradition decay`],
    ["MsgNavyTraditionDecay", (icon: string, amount: string) => `${icon} ${amount}% Navy tradition decay`],
    ["MsgInfantryCost", (icon: string, amount: string) => `${icon} ${amount}% Infantry cost`],
    ["MsgCavalryCost", (icon: string, amount: string) => `${icon} ${amount}% Cavalry cost`],
    ["MsgArtilleryCost", (icon: string, amount: string) => `${icon} ${amount}% Artillery cost`],
    ["MsgMILTechCost", (icon: string, amount: string) => `${icon} ${amount}% Military technology cost`],
    ["MsgHostileCoreCreation", (icon: string, amount: string) => `${icon} ${amount}% Hostile core-creation cost on us`],
    ["MsgCaravanPower", (icon: string, amount: string) => `${icon} ${amount}% Caravan power`],
    ["MsgLandLeaderFire", (icon: string, amount: string) => `${icon} ${amount} Land leader fire`],
    ["MsgLandLeaderShock", (icon: string, amount: string) => `${icon} ${amount} Land leader shock`],
    ["MsgLandLeaderManeuver", (icon: string, amount: string) => `${icon} ${amount} Land leader maneuver`],
    ["MsgLeaderSiege", (icon: string, amount: string) => `${icon} ${amount} Leader siege`],
    ["MsgFortDefense", (icon: string, amount: string) => `${icon} ${amount}% Fort defense`],
    ["MsgFortMaintenance", (icon: string, amount: string) => `${icon} ${amount}% Fort maintenance`],
    ["MsgReinforceSpeed", (icon: string, amount: string) => `${icon} ${amount}% Reinforce speed`],
    ["MsgAttritionForEnemies", (icon: string, amount: string) => `${icon} ${amount}% Attrition for enemies`],
    ["MsgSiegeAbility", (icon: string, amount: string) => `${icon} ${amount}% Siege ability`],
    ["MsgRecoverArmyMoraleSpeed", (icon: string, amount: string) => `${icon} ${amount}% Recover army morale speed`],
    ["MsgTradeRange", (icon: string, amount: string) => `${icon} ${amount}% Trade range`],
    ["MsgTradeSteering", (icon: string, amount: string) => `${icon} ${amount}% Trade steering`],
    ["MsgTextIs", (what: string) => `Text is: ''${what}''`],
    ["MsgAnyOwnedPlanet", () => "Any owned planet:"],
    ["MsgAnyOwnedShip", () => "Any owned ship:"],
    ["MsgAnyPop", () => "Any pop:"],
    ["MsgEveryOwnedPlanet", () => "Every owned planet:"],
    ["MsgEveryOwnedPop", () => "Every pop on owned planets:"],
    ["MsgRandomOwnedShip", () => "One random owned ship:"],
    ["MsgRandomPop", () => "One random pop:"],
    ["MsgRandomSystem", () => "One random system:"],
    ["MsgRandomTile", () => "One random tile:"],

    ["MsgGainTrait", (icon: string, what: string) => `Gain trait ${icon} ${what}`],
    ["MsgAbsolutism", (icon: string, amount: string) => `${icon} Absolutism is at least ${amount}`],
    ["MsgGainAbsolutism", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} absolutism`],
    ["MsgMaxAbsolutism", (icon: string, amount: string) => `${icon} ${amount} Maximum absolutism`],
    ["MsgYearlyAbsolutism", (icon: string, amount: string) => `${icon} ${amount} Yearly absolutism`],
    ["MsgCurrentAge", (icon: string, what: string) => `It is currently the ${icon} ${what}`],
    ["MsgAcceptedCulture", (icon: string, what: string) => `${icon} ${what} is accepted culture`],
    ["MsgCalcTrueIf", (amount: string) => `At least ${amount} of the following are true:`],
    ["MsgGainConstructionProgress", (amount: string) => `${gainOrLose(amount)} ${amount} progress towards completing the great project`],
    ["MsgGainHarmonizationProgress", (amount: string) => `${gainOrLose(amount)} ${amount} progress towards harmonization`],
    ["MsgGainHeirSupport", (amount: string) => `${gainOrLose(amount)} ${amount} support for our heir`],
    ["MsgGainYearsOfSeparatism", (amount: string) => `${gainOrLose(amount)} ${amount} years of separatism`],
    ["MsgAuth", (amount: string) => `Authority is at least ${amount}`],
    ["MsgGainColonyPopulation", (amount: string) => `${gainOrLose(amount)} ${amount} population`],
    ["MsgGainCorruption", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} corruption`],
    ["MsgGainDevastation", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} devastation`],
    ["MsgGainHarmony", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} harmony`],
    ["MsgGainMilitarization", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} militarization`],
    ["MsgGainProsperity", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} progress towards prosperity`],
    ["MsgGainSplendor", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} splendor`],
    ["MsgAddTariffValue", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} tariffs`],
    ["MsgGainYearlySailors", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} year's worth of sailors`],
    ["MsgAdminEfficiencyBonus", (icon: string, amount: string) => `${icon} ${amount} administrative efficiency`],
    ["MsgAdminEfficiency", (icon: string, amount: string) => `${icon} Administrative efficiency is at least ${amount}`],
    ["MsgDisasterMod", () => "disaster modifier"],
    ["MsgAddClaimFor", (who: string) => `${who} gains a claim on this province`],
    ["MsgAddClaimOn", (where: string) => `Gain a claim on ${where}`],
    ["MsgAddAcceptedCulture", (icon: string, what: string) => `${icon} Gain ${what} as an accepted culture`],
    ["MsgAddBuilding", (icon: string, what: string) => `Build ${icon} ${what}`],
    ["MsgAddHarmonizedReligion", (icon: string, what: string) => `Gain ${icon} ${what} as a harmonized religion`],
    ["MsgAddHeirPersonality", (icon: string, what: string) => `Heir gains the personality trait ${icon} ${what}`],
    ["MsgAddConsortPersonality", (icon: string, what: string) => `Consort gains the personality trait ${icon} ${what}`],
    ["MsgAddRulerPersonality", (icon: string, what: string) => `Ruler gains the personality trait ${icon} ${what}`],
    ["MsgAddCenterOfReformation", (icon: string, what: string) => `Create a ${icon} ${what} Center of Reformation`],
    ["MsgAddHistoricalRival", (who: string) => `Add ${who} as a historical rival`],
    ["MsgAddTruceWith", (who: string) => `Create a truce with ${who}`],
    ["MsgGainSailors", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} sailors`],
    ["MsgGainSailorsFrac", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} sailors equal to ${amount} of maximum`],
    ["MsgArmyProfessionalism", (icon: string, amount: string) => `${icon} Army professionalism is at least ${amount}`],
    ["MsgArmyProfessionalismAs", (icon: string, whom: string) => `${icon} Army professionalism is at least that of ${whom}`],
    ["MsgGainArmyProfessionalism", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} army professionalism`],
    ["MsgSailorsPercentage", (icon: string, amount: string) => `${icon} Sailors reserves are at least ${amount} of maximum`],
    ["MsgNationalSailorsMod", (icon: string, amount: string) => `${icon} ${amount} National sailors modifier`],
    ["MsgCorruption", (icon: string, amount: string) => `${icon} Corruption is at least ${amount}`],
    ["MsgAddIncidentVariableValue", (amount: string) => `The country moves towards the ${toNumber(amount) < 0 ? "Open" : "Isolationist"} end of the current incident by ${Math.abs(toNumber(amount))}`],
    ["MsgAddInstitutionEmbracement", (icon: string, what: string, amount: string) => `${gainOrLose(amount)} ${amount} progress towards the ${icon} ${what} institution`],
    ["MsgAddIsolationism", (amount: string) => `Become ${amount} steps more ${toNumber(amount) < 0 ? "Open" : "Isolationist"}`],
    ["MsgGainMandate", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${amount} Mandate`],
    ["MsgAddMandateEffect", () => "{{add mandate effect}}"],
    ["MsgAddMandateLargeEffect", () => "{{add mandate effect|large=yes}}"],
    ["MsgAddMeritocracyEffect", () => "{{add meritocracy effect}}"],
    ["MsgAddMeritocracyLargeEffect", () => "{{add meritocracy effect|large=yes}}"],
    
    ["MsgMutualOpinion", (modid: string, what: string, whom: string) => `This country and ${whom} gain opinion modifier ${textInQuotes(what)} <!-- ${modid} --> towards each other`],
    ["MsgMutualOpinionDur", (what: string, whom: string, days: string) => `This country and ${whom} gain opinion modifier ${textInQuotes(what)} towards each other for ${days} ${pluralOrSingle(days, "day", "days")}`],
    ["MsgAddNextInstitutionEmbracement", (amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} progress towards the next non-present institution`],
    ["MsgAddSpyNetworkFrom", (whom: string, amount: string) => `${whom} ${gainOrLose(amount)} ${coloredNumber(amount)} spy network strength`],
    ["MsgAddSpyNetworkIn", (whom: string, amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} spy network strength in ${whom}`],
    ["MsgEventTarget", (tag: string) => `Event target <tt>${tag}</tt>:`],
    ["MsgEventTargetVar", (tag: string) => `event target <tt>${tag}</tt>`],
    ["MsgSudebnikProgress", (amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} Sudebnik progress`],
    ["MsgOprichninaProgress", (amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} Oprichnina progress`],
    ["MsgStreltsyProgress", (amount: string) => `${gainOrLose(amount)} ${coloredNumber(amount)} Streltsy progress`],
    ["MsgAddLootFromProvinceEffect", () => "Gain {{icon|ducats}} ducats and {{icon|mil}} military power scaling with province development"],
    ["MsgAddEstateLoyaltyEffect", (whom: string) => `{{add estate loyalty effect|${whom}}}`],
    ["MsgReduceEstateLoyaltyEffect", (whom: string) => `{{add estate loyalty effect|${whom}|reduce}}`],
    ["MsgAddStabilityOrAdm", () => "{{add stability or adm power}}"],
    ["MsgAddTrust", (whom: string, amount: string) => `Gain ${coloredNumber(amount)} trust towards ${whom}`],
    ["MsgAddTrustMutual", (whom: string, amount: string) => `This country and ${whom} gain ${coloredNumber(amount)} trust towards each other`],
    ["MsgSaveEventTargetAs", (name: string) => `Save as event target named <tt>${name}</tt>`],
    ["MsgHasSavedEventTarget", (name: string) => `An event target named <tt>${name}</tt> has been saved`],
    ["MsgRemoveClaim", (who: string) => `${who} loses their claim on this province`],
    ["MsgTribalAllegianceBonus", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} {{DLC-only|Yearly tribal allegiance}}`],
    ["MsgTribalAllegiance", (icon: string, amount: string) => `${icon} {{DLC-only|Tribal allegiance}} is at least ${amount}`],
    ["MsgGainTribalAllegiance", (icon: string, amount: string) => `${gainOrLose(amount)} ${icon} ${coloredNumber(amount)} {{DLC-only|tribal allegiance}}`],
    ["MsgArmySizePc", (amount: string) => `Army size is at least ${displayPercentage(amount)} of force limit`],

    // use add_unit_construction instead
    // ["MsgBuildHeavyShips", (icon: string, amount: string, speed: string, cost: string) => `Build ${icon} ${reducedNum(plainNum, amount)} heavy ships at ${plainPc(cost)} of normal cost, taking ${plainPc(speed)} of normal time`],
    // ["MsgBuildLightShips", (icon: string, amount: string, speed: string, cost: string) => `Build ${icon} ${reducedNum(plainNum, amount)} light ships at ${plainPc(cost)} of normal cost, taking ${plainPc(speed)} of normal time`],
    // ["MsgBuildGalleys", (icon: string, amount: string, speed: string, cost: string) => `Build ${icon} ${reducedNum(plainNum, amount)} galleys at ${plainPc(cost)} of normal cost, taking ${plainPc(speed)} of normal time`],
    // ["MsgBuildTransports", (icon: string, amount: string, speed: string, cost: string) => `Build ${icon} ${reducedNum(plainNum, amount)} transports at ${plainPc(cost)} of normal cost, taking ${plainPc(speed)} of normal time`],

    // not used ?
    // ["MsgAristocratsInfluence", (icon: string, amount: string) => `${icon} ${reducedNum(plainPcSign, amount)} The Aristocrats influence`],
    ["MsgDomesticTradePower", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Domestic trade power`],
    ["MsgEmbracementCost", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} Institution embracement cost`],
    ["MsgGlobalTaxIncome", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Tax income`],
    ["MsgHeavyShipCost", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} Heavy ship cost`],
    ["MsgHeirChance", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Chance of new heir`],
    ["MsgInstitutionSpread", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Institution spread`],
    ["MsgLandFireDamage", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Land fire damage`],
    ["MsgLocalConstructionCost", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} Local construction cost`],
    ["MsgLocalCultureConversionCost", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} Local culture conversion cost`],
    ["MsgLocalDefensiveness", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local defensiveness`],
    ["MsgLocalGoodsProduced", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Local goods produced`],
    ["MsgLocalGoodsProducedMod", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local goods produced modifier`],
    ["MsgLocalHostileMovementSpeed", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} Local hostile movement speed`],
    ["MsgLocalInstitutionSpread", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local institution spread`],
    ["MsgLocalUnrest", (icon: string, amount: string) => `${icon} ${numberSigned(amount)} Local unrest`],
    ["MsgLocalManpowerMod", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local manpower modifier`],
    ["MsgLocalMissionaryStrength", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local missionary strength`],
    ["MsgLocalMonthlyDevastation", (icon: string, amount: string) => `${icon} ${numberSigned(amount)} Monthly devastation`],
    ["MsgLocalProdEff", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local production efficiency`],
    ["MsgLocalSettlerIncrease", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Local settler increase`],
    ["MsgLocalStateMaintMod", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} State maintenance`],
    ["MsgLocalTaxMod", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local tax modifier`],
    ["MsgLocalTradePower", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Local trade power`],
    ["MsgLocalTradePowerMod", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Local trade power modifier`],
    ["MsgMaxPromotedCultures", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Max promoted cultures`],

    ["MsgMercenaryDiscipline", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Mercenary discipline`],
    ["MsgMeritocracy", (icon: string, amount: string) => `${icon} Meritocracy is at least ${amount}`],
    ["MsgProvTradePowerMod", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Provincial trade power modifier`],
    ["MsgRazingPowerGain", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Razing power gain`],
    ["MsgRecoverNavyMoraleSpeed", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Recover navy morale speed`],
    ["MsgStateMaintMod", (icon: string, amount: string) => `${icon} ${displayPercentageSigned(amount)} State maintenance`],
    ["MsgSubjectLibertyDesire", (icon: string, amount: string) => `${icon} -${displayPercentage(amount)} Liberty desire in subjects`],
    ["MsgTaxIncome", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Tax income`],
    ["MsgTradePowerAbroad", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Trade power abroad`],
    ["MsgTradeValueMod", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Trade value modifier`],
    ["MsgYearlyArmyProfessionalism", (icon: string, amount: string) => `${icon} ${coloredPercentageSigned(amount)} Yearly army professionalism`],
    ["MsgYearlyCorruption", (icon: string, amount: string) => `${icon} ${numberSigned(amount)} Yearly corruption`],
    ["MsgYearlyMeritocracy", (icon: string, amount: string) => `${icon} ${coloredNumberSigned(amount)} Yearly meritocracy`],
    ["MsgAddInnovativenessBigEffect", () => "If DLC {{icon|rb}} Rule Britannia is active, gain {{icon|innovativeness}} {{green|3}} innovativeness"],
    ["MsgAddInnovativenessSmallEffect", () => "If DLC {{icon|rb}} Rule Britannia is active, gain {{icon|innovativeness}} {{green|1}} innovativeness"],
    ["MsgAddReformProgressMediumEffect", () => "If DLC {{icon|dhr}} Dharma is active, gain {{icon|reform progress}} {{green|25}} reform progress"],
    ["MsgAddReformProgressSmallEffect", () => "If DLC {{icon|dhr}} Dharma is active, gain {{icon|reform progress}} {{green|15}} reform progress"],
    ["MsgBoostBureaucratsEffect", () => "If DLC {{icon|moh}} Mandate of Heaven is ''not'' active, the {{icon|bureaucrats}} Grand Secretariat faction gains '''10''' influence"],
    ["MsgBoostBureaucratsLargeEffect", () => "If DLC {{icon|moh}} Mandate of Heaven is ''not'' active, the {{icon|bureaucrats}} Grand Secretariat faction gains '''15''' influence"],
    ["MsgBoostEunuchsEffect", () => "If DLC {{icon|moh}} Mandate of Heaven is ''not'' active, the {{icon|eunuchs}} Offices of Maritime Trade faction gains '''10''' influence"],
    ["MsgBoostEunuchsLargeEffect", () => "If DLC {{icon|moh}} Mandate of Heaven is ''not'' active, the {{icon|eunuchs}} Offices of Maritime Trade faction gains '''15''' influence"],
    ["MsgBoostTemplesEffect", () => "If DLC {{icon|moh}} Mandate of Heaven is ''not'' active, the {{icon|temples}} Commanderies of the Five Armies faction gains '''10''' influence"],
    ["MsgBoostTemplesLargeEffect", () => "If DLC {{icon|moh}} Mandate of Heaven is ''not'' active, the {{icon|temples}} Commanderies of the Five Armies faction gains '''15''' influence"],
    ["MsgCheckIfNonStateAdvisorEffect", () => "Randomly set a country flag to determine the religion (state, secondary, tertiary, or Jewish) of an advisor based on location of the capital and state religion group"],
    ["MsgEraseAdvisorFlagsEffect", () => "Forget the choice of religion for an advisor"],
    ["MsgIncreaseHeirAdmEffect", () => "Heir gains {{icon|adm}} {{green|1}} administrative skill, or gain {{green|50}} administrative power if skill is already 6"],
    ["MsgIncreaseHeirDipEffect", () => "Heir gains {{icon|dip}} {{green|1}} diplomatic skill, or gain {{green|50}} diplomatic power if skill is already 6"],
    ["MsgIncreaseHeirMilEffect", () => "Heir gains {{icon|mil}} {{green|1}} military skill, or gain {{green|50}} military power if skill is already 6"],
    ["MsgIncreaseLegitimacyMediumEffect", () => "Gain {{icon|legitimacy}} {{green|10}} legitimacy, {{icon|horde unity}} {{green|10}} horde unity, {{icon|devotion}} {{green|10}} devotion, or {{icon|republican tradition}} {{green|5}} republican tradition as appropriate"],
    ["MsgIncreaseLegitimacySmallEffect", () => "Gain {{icon|legitimacy}} {{green|5}} legitimacy, {{icon|horde unity}} {{green|5}} horde unity, {{icon|devotion}} {{green|5}} devotion, or {{icon|republican tradition}} {{green|2.5}} republican tradition as appropriate"],
    ["MsgMoveCapitalEffect", () => "Province becomes the new {{icon|capital}} capital. If it was in the empire and the country isn't, it is removed from the empire."],
    ["MsgReduceBureaucratsEffect", () => "If DLC Mandate of Heaven is ''not'' active, the Grand Secretariat faction loses 10 influence"],
    ["MsgReduceEunuchsEffect", () => "If DLC Mandate of Heaven is ''not'' active, the Offices of Maritime Trade faction loses 10 influence"],
    ["MsgReduceTemplesEffect", () => "If DLC Mandate of Heaven is ''not'' active, the Commanderies of the Five Armies faction loses 10 influence"],
    ["MsgReduceLegitimacyEffect", () => "Lose {{icon|legitimacy}} {{red|10}} legitimacy, {{icon|horde unity}} {{red|10}} horde unity, {{icon|devotion}} {{red|10}} devotion, or {{icon|republican tradition}} {{red|5}} republican tradition as appropriate"],
    ["MsgReduceLegitimacySmallEffect", () => "Lose {{icon|legitimacy}} {{red|5}} legitimacy, {{icon|horde unity}} {{red|5}} horde unity, {{icon|devotion}} {{red|5}} devotion, or {{icon|republican tradition}} {{red|2.5}} republican tradition as appropriate"],
    ["MsgReduceMandateEffect", () => "If the country is the Emperor of China and DLC {{icon|moh}} Mandate of Heaven is active, lose {{icon|mandate}} {{red|5}} mandate"],
    ["MsgReduceMandateLargeEffect", () => "If the country is the Emperor of China and DLC {{icon|moh}} Mandate of Heaven is active, lose {{icon|mandate}} {{red|10}} mandate"],
    ["MsgReduceMeritocracyEffect", () => "If the country is the Emperor of China and DLC {{icon|moh}} Mandate of Heaven is active, lose {{icon|meritocracy}} {{red|5}} meritocracy"],
    ["MsgReduceMeritocracyLargeEffect", () => "If the country is the Emperor of China and DLC {{icon|moh}} Mandate of Heaven is active, lose {{icon|meritocracy}} {{red|10}} meritocracy"],
    ["MsgReduceReformProgressSmallEffect", () => "If DLC {{icon|dhr}} Dharma is active, lose {{icon|reform progress}} {{red|25}} reform progress"],
    ["MsgReduceReformProgressBigEffect", () => "If DLC {{icon|dhr}} Dharma is active, lose {{icon|reform progress}} {{red|75}} reform progress"],
    ["MsgRemoveAdvisorAdmEffect", () => "The currently employed administrative advisor leaves the country's court."],
    ["MsgDivorceConsortEffect", () => "Attempt to divorce the consort. The consort's family may be offended by this, spoiling relations, giving them a casus belli, or angering local nobles."],
    ["MsgAddGovernmentReform", (what: string) => `Enact government reform ${what}`],
    ["MsgAddCOTLevel", (icon: string, amount: string) => `Gain a ${icon} level ${amount} Center of Trade`],
    ["MsgRulerAge", (amount: string) => `Ruler is at least ${amount} years old`]
]);